" Depends: junegunn/vim-plug

" Put plugins and dictionaries in this dir (also on Windows)
let vimDir = '$HOME/.vim'
let &runtimepath.=','.vimDir

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'

set laststatus=2
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
" Have the NERDTree on startup (left side)
autocmd vimenter * NERDTree
" Close NERDTree if it is the only window left
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <Leader>n <plug>NERDTreeTabsToggle<CR>

Plug 'kien/rainbow_parentheses.vim'
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

Plug 'airblade/vim-gitgutter'
Plug 'benmills/vimux'
Plug 'chrisbra/csv.vim'
Plug 'daviddavis/vim-colorpack'
Plug 'digitaltoad/vim-pug'
Plug 'edkolev/tmuxline.vim'
Plug 'edsono/vim-matchit'
Plug 'godlygeek/tabular'
Plug 'hail2u/vim-css3-syntax'
Plug 'jmcantrell/vim-virtualenv'
Plug 'kchmck/vim-coffee-script'
Plug 'lifepillar/pgsql.vim'
Plug 'mhinz/vim-signify'
Plug 'mhinz/vim-tmuxify'
Plug 'mileszs/ack.vim'
Plug 'othree/html5.vim'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'pangloss/vim-javascript'
Plug 'pbrisbin/html-template-syntax'
Plug 'scrooloose/nerdcommenter'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-jp/cpp-vim'
Plug 'lokaltog/vim-powerline'
Plug 'scrooloose/syntastic'

let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'

let g:syntastic_python_checkers = []

Plug 'shougo/neocomplcache'

let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3

inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

"autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
"autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
"autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
"autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
"autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

Plug 'mattn/webapi-vim'
Plug 'mattn/gist-vim'

let g:gist_clip_command = 'xclip -selection clipboard'
let g:gist_detect_filetype = 1
let g:gist_show_privates = 1
let g:gist_post_private = 1
let g:gist_get_multiplefile = 1

Plug 'shougo/unite.vim'
Plug 'osyo-manga/unite-quickfix'

Plug 'dag/vim2hs'

let g:haskell_conceal = 0
let g:haskell_conceal_enumerations = 0

Plug 'sjl/gundo.vim'

let g:gundo_right = 1

map <Leader>u :GundoToggle<CR>

Plug 'klen/python-mode'

:let g:pymode_python = 'python3'

" Initialize plugin system
call plug#end()

highlight WhiteSpaceEol ctermbg=darkgreen guibg=lightgreen
highlight Tabs ctermbg=darkred guibg=lightred
hi CursorColumn gui=NONE guibg=#000000
hi! link CursorColumn CursorLine

let g:whiteSpaceColor = 1

function ToggleWhiteSpaceColor()
  if g:whiteSpaceColor
    let g:whiteSpaceColor = 0
  else
    let g:whiteSpaceColor = 1
  end
  call WhiteSpaceColorCallback()
endfunction

function WhiteSpaceColorCallback()
  if g:whiteSpaceColor
    if !exists("w:match_WhiteSpaceEol")
      let w:match_WhiteSpaceEol = matchadd('WhiteSpaceEol', '\s\+$', -1)
    end

    if !exists("w:match_Tabs")
      let w:match_Tabs = matchadd('Tabs', '\t', -1)
    end
  else
    if exists("w:match_WhiteSpaceEol")
      call matchdelete(w:match_WhiteSpaceEol)
      unlet w:match_WhiteSpaceEol
    end

    if exists("w:match_Tabs")
      call matchdelete(w:match_Tabs)
      unlet w:match_Tabs
    end
  end
endfunction

au BufWinEnter * call WhiteSpaceColorCallback()

runtime ftplugin/man.vim

" Options
set background=dark
set expandtab
set history=10000
set hls
set incsearch
set mouse=a
set nobackup
set notimeout
set noshowmode
set number
set shiftwidth=2
set showcmd
set showmatch
set softtabstop=0
set t_Co=256
set tabstop=8
set keymap=greek_utf-8
set iminsert=0
set imsearch=0

set ttimeout
set ttimeoutlen=0

let g:netrw_altv = 1

" Keep undo history across sessions by storing it in a file
if has('persistent_undo')
  let myUndoDir = expand(vimDir . '/undodir')
  " Create dirs
  call system('mkdir ' . vimDir)
  call system('mkdir ' . myUndoDir)
  let &undodir = myUndoDir
  set undofile
  set undolevels=16384
  set undoreload=16384
endif

" Fn mappings
map <F2>  :set cursorline!<CR>
map <F3>  :set cursorcolumn!<CR>
map <F4>  :call ToggleWhiteSpaceColor()<CR>
map <F5>  :set wrap!<CR>
map <F6>  :if exists("g:syntax_on") <Bar> syntax off <Bar> else <Bar> syntax enable <Bar> endif<CR>
map <F7>  :set scrollbind!<CR>
map <F8>  :noh<CR>
map <F10> `[v`]
map <F11> @@
map <F13> @:

let g:Powerline_symbols = 'fancy'
set fillchars+=stl:\ ,stlnc:\

syntax on
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
filetype plugin indent on

